# Generated by Django 4.2.9 on 2024-01-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatfournisseur',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
