# Generated by Django 4.2.9 on 2024-01-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_achatfournisseur_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nom',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='prenom',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
