# Generated by Django 4.2.9 on 2024-01-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_reservation_nom_reservation_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteclient',
            name='mode_paiement',
            field=models.CharField(choices=[('Cheque', 'cheque'), ('CB', 'cb'), ('Especes', 'especes')], max_length=50),
        ),
    ]
