# Generated by Django 4.2.9 on 2024-01-08 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_rename_date_achat_venteclient_date_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venteclient',
            name='utilisateur_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.client'),
        ),
    ]
