# Generated by Django 4.2.9 on 2024-01-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_venteclient_utilisateur_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse_client',
            field=models.TextField(blank=True, default='Unknown'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='Unknown,', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_client',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, default='Unknown', max_length=10),
        ),
    ]
