# Generated by Django 4.2.9 on 2024-01-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_client_adresse_client_alter_client_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Depense',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='produit',
        ),
        migrations.DeleteModel(
            name='VenteQuotidienne',
        ),
        migrations.RemoveField(
            model_name='client',
            name='achats',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
