# Generated by Django 4.2.9 on 2024-01-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_delete_depense_remove_stocks_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='derniere_date_achat',
        ),
    ]
