# Generated by Django 4.2.9 on 2024-01-06 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(default='Unknown', max_length=255)),
                ('prenom', models.CharField(default='Unknown', max_length=255)),
                ('telephone', models.CharField(default='Unknown', max_length=10)),
                ('email', models.EmailField(default='Unknown', max_length=254)),
                ('adresse_client', models.TextField(default='Unknown')),
                ('achats', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('derniere_date_achat', models.DateField(blank=True, null=True)),
                ('newsletter', models.CharField(choices=[('Oui', 'oui'), ('Non', 'non')], default='Non', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Unknown')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_achat', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(default='Unknown', max_length=255)),
                ('adresse_fournisseur', models.TextField(default='Unknown')),
                ('telephone', models.CharField(default='Unknown', max_length=10)),
                ('email', models.EmailField(default='Unknown', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FournisseurProduit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Unknown', max_length=255)),
                ('quantite', models.IntegerField(default=0)),
                ('provenance', models.CharField(default='Unknown', max_length=255)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('fournisseur', models.ManyToManyField(through='API.FournisseurProduit', to='API.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='VenteQuotidienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField(default=django.utils.timezone.now)),
                ('total_ventes', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UtilisateurAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default=None, max_length=30, unique=True)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('password', models.CharField(default=None, max_length=128)),
                ('status_utilisateur', models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client')], default='Client', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VenteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vendue', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_achat', models.DateField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.produit')),
                ('utilisateur_client', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.client')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_entree', models.IntegerField(default=0)),
                ('quantite_sortie', models.IntegerField(default=0)),
                ('date_achat', models.DateField(default=django.utils.timezone.now)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('date_reservation', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('Confirmé', 'Confirmé'), ('Annulé', 'Annulé')], max_length=20)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.client')),
            ],
        ),
        migrations.AddField(
            model_name='fournisseurproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.produit'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='type_produit',
            field=models.ManyToManyField(related_name='fournisseurs_produits', through='API.FournisseurProduit', to='API.produit'),
        ),
        migrations.AddField(
            model_name='client',
            name='utilisateur_client',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AchatFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_achete', models.IntegerField(default=0)),
                ('date_achat', models.DateField(default=django.utils.timezone.now)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.produit')),
            ],
        ),
    ]
