# Generated by Django 4.2.9 on 2024-01-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_venteclient_mode_paiement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venteclient',
            old_name='date_achat',
            new_name='date_vente',
        ),
    ]
